import { StyleSheet, View } from "react-native";
import React from "react";
import { InputBlock } from "./InputBlock";
import { AntDesign } from "@expo/vector-icons";

export const AllIcons = () => {
  return (
    <View style={styles.body}>
      <InputBlock
        position={"start"}
        icon={"search1"}
        placeholder={"Meklēt vietu vai adresi"}
      />
      <AntDesign name={"arrowright"} size={24} color="black" />
      <AntDesign name={"form"} size={24} color={"black"} />
      <AntDesign name={"picture"} size={24} color={"black"} />
      <AntDesign name={"table"} size={24} color={"black"} />
      <AntDesign name={"filter"} size={24} color={"black"} />
      <AntDesign name={"stepforward"} size={24} color={"black"} />
      <AntDesign name={"stepbackward"} size={24} color={"black"} />
      <AntDesign name={"forward"} size={24} color={"black"} />
      <AntDesign name={"banckward"} size={24} color={"black"} />
      <AntDesign name={"caretright"} size={24} color={"black"} />
      <AntDesign name={"caretleft"} size={24} color={"black"} />
      <AntDesign name={"caretdown"} size={24} color={"black"} />
      <AntDesign name={"caretup"} size={24} color={"black"} />
      <AntDesign name={"rightcircle"} size={24} color={"black"} />
      <AntDesign name={"leftcircle"} size={24} color={"black"} />
      <AntDesign name={"upcircle"} size={24} color={"black"} />
      <AntDesign name={"downcircle"} size={24} color={"black"} />
      <AntDesign name={"rightcircleo"} size={24} color={"black"} />
      <AntDesign name={"leftcircleo"} size={24} color={"black"} />
      <AntDesign name={"upcircleo"} size={24} color={"black"} />
      <AntDesign name={"downcircleo"} size={24} color={"black"} />
      <AntDesign name={"verticleleft"} size={24} color={"black"} />
      <AntDesign name={"verticleright"} size={24} color={"black"} />
      <AntDesign name={"back"} size={24} color={"black"} />
      <AntDesign name={"retweet"} size={24} color={"black"} />
      <AntDesign name={"shrink"} size={24} color={"black"} />
      <AntDesign name={"arrowsalt"} size={24} color={"black"} />
      <AntDesign name={"doubleright"} size={24} color={"black"} />
      <AntDesign name={"doubleleft"} size={24} color={"black"} />
      <AntDesign name={"arrowdown"} size={24} color={"black"} />
      <AntDesign name={"arrowup"} size={24} color={"black"} />
      <AntDesign name={"arrowright"} size={24} color={"black"} />
      <AntDesign name={"arrowleft"} size={24} color={"black"} />
      <AntDesign name={"down"} size={24} color={"black"} />
      <AntDesign name={"up"} size={24} color={"black"} />
      <AntDesign name={"right"} size={24} color={"black"} />
      <AntDesign name={"left"} size={24} color={"black"} />
      <AntDesign name={"minussquareo"} size={24} color={"black"} />
      <AntDesign name={"minuscircle"} size={24} color={"black"} />
      <AntDesign name={"minuscircleo"} size={24} color={"black"} />
      <AntDesign name={"minus"} size={24} color={"black"} />
      <AntDesign name={"pluscircleo"} size={24} color={"black"} />
      <AntDesign name={"pluscircle"} size={24} color={"black"} />
      <AntDesign name={"plus"} size={24} color={"black"} />
      <AntDesign name={"infocirlce"} size={24} color={"black"} />
      <AntDesign name={"infocirlceo"} size={24} color={"black"} />
      <AntDesign name={"info"} size={24} color={"black"} />
      <AntDesign name={"exclamation"} size={24} color={"black"} />
      <AntDesign name={"exclamationcircle"} size={24} color={"black"} />
      <AntDesign name={"exclamationcircleo"} size={24} color={"black"} />
      <AntDesign name={"closecircle"} size={24} color={"black"} />
      <AntDesign name={"closecircleo"} size={24} color={"black"} />
      <AntDesign name={"checkcircle"} size={24} color={"black"} />
      <AntDesign name={"checkcircleo"} size={24} color={"black"} />
      <AntDesign name={"check"} size={24} color={"black"} />
      <AntDesign name={"close"} size={24} color={"black"} />
      <AntDesign name={"customerservice"} size={24} color={"black"} />
      <AntDesign name={"creditcard"} size={24} color={"black"} />
      <AntDesign name={"codesquareo"} size={24} color={"black"} />
      <AntDesign name={"book"} size={24} color={"black"} />
      <AntDesign name={"barschart"} size={24} color={"black"} />
      <AntDesign name={"bars"} size={24} color={"black"} />
      <AntDesign name={"question"} size={24} color={"black"} />
      <AntDesign name={"questioncircle"} size={24} color={"black"} />
      <AntDesign name={"questioncircleo"} size={24} color={"black"} />
      <AntDesign name={"pause"} size={24} color={"black"} />
      <AntDesign name={"pausecircle"} size={24} color={"black"} />
      <AntDesign name={"pausecircleo"} size={24} color={"black"} />
      <AntDesign name={"clockcircle"} size={24} color={"black"} />
      <AntDesign name={"clockcircleo"} size={24} color={"black"} />
      <AntDesign name={"swap"} size={24} color={"black"} />
      <AntDesign name={"swapleft"} size={24} color={"black"} />
      <AntDesign name={"swapright"} size={24} color={"black"} />
      <AntDesign name={"plussquareo"} size={24} color={"black"} />
      <AntDesign name={"frown"} size={24} color={"black"} />
      <AntDesign name={"menufold"} size={24} color={"black"} />
      <AntDesign name={"mail"} size={24} color={"black"} />
      <AntDesign name={"areachart"} size={24} color={"black"} />
      <AntDesign name={"linechart"} size={24} color={"black"} />
      <AntDesign name={"home"} size={24} color={"black"} />
      <AntDesign name={"laptop"} size={24} color={"black"} />
      <AntDesign name={"star"} size={24} color={"black"} />
      <AntDesign name={"staro"} size={24} color={"black"} />
      <AntDesign name={"meho"} size={24} color={"black"} />
      <AntDesign name={"meh"} size={24} color={"black"} />
      <AntDesign name={"shoppingcart"} size={24} color={"black"} />
      <AntDesign name={"save"} size={24} color={"black"} />
      <AntDesign name={"user"} size={24} color={"black"} />
      <AntDesign name={"videocamera"} size={24} color={"black"} />
      <AntDesign name={"totop"} size={24} color={"black"} />
      <AntDesign name={"team"} size={24} color={"black"} />
      <AntDesign name={"sharealt"} size={24} color={"black"} />
      <AntDesign name={"setting"} size={24} color={"black"} />
      <AntDesign name={"phone"} size={24} color={"black"} />
      <AntDesign name={"paperclip"} size={24} color={"black"} />
      <AntDesign name={"notification"} size={24} color={"black"} />
      <AntDesign name={"menuunfold"} size={24} color={"black"} />
      <AntDesign name={"inbox"} size={24} color={"black"} />
      <AntDesign name={"lock"} size={24} color={"black"} />
      <AntDesign name={"qrcode"} size={24} color={"black"} />
      <AntDesign name={"tags"} size={24} color={"black"} />
      <AntDesign name={"tagso"} size={24} color={"black"} />
      <AntDesign name={"cloudo"} size={24} color={"black"} />
      <AntDesign name={"cloud"} size={24} color={"black"} />
      <AntDesign name={"cloudupload"} size={24} color={"black"} />
      <AntDesign name={"clouddownload"} size={24} color={"black"} />
      <AntDesign name={"clouddownloado"} size={24} color={"black"} />
      <AntDesign name={"clouduploado"} size={24} color={"black"} />
      <AntDesign name={"enviroment"} size={24} color={"black"} />
      <AntDesign name={"enviromento"} size={24} color={"black"} />
      <AntDesign name={"eye"} size={24} color={"black"} />
      <AntDesign name={"eyeo"} size={24} color={"black"} />
      <AntDesign name={"camera"} size={24} color={"black"} />
      <AntDesign name={"camerao"} size={24} color={"black"} />
      <AntDesign name={"windows"} size={24} color={"black"} />
      <AntDesign name={"export2"} size={24} color={"black"} />
      <AntDesign name={"export"} size={24} color={"black"} />
      <AntDesign name={"circledowno"} size={24} color={"black"} />
      <AntDesign name={"circledown"} size={24} color={"black"} />
      <AntDesign name={"hdd"} size={24} color={"black"} />
      <AntDesign name={"ie"} size={24} color={"black"} />
      <AntDesign name={"delete"} size={24} color={"black"} />
      <AntDesign name={"enter"} size={24} color={"black"} />
      <AntDesign name={"pushpino"} size={24} color={"black"} />
      <AntDesign name={"pushpin"} size={24} color={"black"} />
      <AntDesign name={"heart"} size={24} color={"black"} />
      <AntDesign name={"hearto"} size={24} color={"black"} />
      <AntDesign name={"smile-circle"} size={24} color={"black"} />
      <AntDesign name={"smileo"} size={24} color={"black"} />
      <AntDesign name={"frowno"} size={24} color={"black"} />
      <AntDesign name={"calculator"} size={24} color={"black"} />
      <AntDesign name={"chrome"} size={24} color={"black"} />
      <AntDesign name={"github"} size={24} color={"black"} />
      <AntDesign name={"iconfontdesktop"} size={24} color={"black"} />
      <AntDesign name={"caretcircleoup"} size={24} color={"black"} />
      <AntDesign name={"upload"} size={24} color={"black"} />
      <AntDesign name={"download"} size={24} color={"black"} />
      <AntDesign name={"piechart"} size={24} color={"black"} />
      <AntDesign name={"lock1"} size={24} color={"black"} />
      <AntDesign name={"unlock"} size={24} color={"black"} />
      <AntDesign name={"windowso"} size={24} color={"black"} />
      <AntDesign name={"dotchart"} size={24} color={"black"} />
      <AntDesign name={"barchart"} size={24} color={"black"} />
      <AntDesign name={"codesquare"} size={24} color={"black"} />
      <AntDesign name={"plussquare"} size={24} color={"black"} />
      <AntDesign name={"minussquare"} size={24} color={"black"} />
      <AntDesign name={"closesquare"} size={24} color={"black"} />
      <AntDesign name={"closesquareo"} size={24} color={"black"} />
      <AntDesign name={"checksquare"} size={24} color={"black"} />
      <AntDesign name={"checksquareo"} size={24} color={"black"} />
      <AntDesign name={"fastbackward"} size={24} color={"black"} />
      <AntDesign name={"fastforward"} size={24} color={"black"} />
      <AntDesign name={"upsquare"} size={24} color={"black"} />
      <AntDesign name={"downsquare"} size={24} color={"black"} />
      <AntDesign name={"leftsquare"} size={24} color={"black"} />
      <AntDesign name={"rightsquare"} size={24} color={"black"} />
      <AntDesign name={"rightsquareo"} size={24} color={"black"} />
      <AntDesign name={"leftsquareo"} size={24} color={"black"} />
      <AntDesign name={"down-square-o"} size={24} color={"black"} />
      <AntDesign name={"up-square-o"} size={24} color={"black"} />
      <AntDesign name={"play"} size={24} color={"black"} />
      <AntDesign name={"playcircleo"} size={24} color={"black"} />
      <AntDesign name={"tag"} size={24} color={"black"} />
      <AntDesign name={"tago"} size={24} color={"black"} />
      <AntDesign name={"addfile"} size={24} color={"black"} />
      <AntDesign name={"folder1"} size={24} color={"black"} />
      <AntDesign name={"file1"} size={24} color={"black"} />
      <AntDesign name={"switcher"} size={24} color={"black"} />
      <AntDesign name={"addfolder"} size={24} color={"black"} />
      <AntDesign name={"folderopen"} size={24} color={"black"} />
      <AntDesign name={"search1"} size={24} color={"black"} />
      <AntDesign name={"ellipsis1"} size={24} color={"black"} />
      <AntDesign name={"calendar"} size={24} color={"black"} />
      <AntDesign name={"filetext1"} size={24} color={"black"} />
      <AntDesign name={"copy1"} size={24} color={"black"} />
      <AntDesign name={"jpgfile1"} size={24} color={"black"} />
      <AntDesign name={"pdffile1"} size={24} color={"black"} />
      <AntDesign name={"exclefile1"} size={24} color={"black"} />
      <AntDesign name={"pptfile1"} size={24} color={"black"} />
      <AntDesign name={"unknowfile1"} size={24} color={"black"} />
      <AntDesign name={"wordfile1"} size={24} color={"black"} />
      <AntDesign name={"dingding"} size={24} color={"black"} />
      <AntDesign name={"dingding-o"} size={24} color={"black"} />
      <AntDesign name={"mobile1"} size={24} color={"black"} />
      <AntDesign name={"tablet1"} size={24} color={"black"} />
      <AntDesign name={"bells"} size={24} color={"black"} />
      <AntDesign name={"disconnect"} size={24} color={"black"} />
      <AntDesign name={"database"} size={24} color={"black"} />
      <AntDesign name={"barcode"} size={24} color={"black"} />
      <AntDesign name={"hourglass"} size={24} color={"black"} />
      <AntDesign name={"flag"} size={24} color={"black"} />
      <AntDesign name={"layout"} size={24} color={"black"} />
      <AntDesign name={"printer"} size={24} color={"black"} />
      <AntDesign name={"USB"} size={24} color={"black"} />
      <AntDesign name={"skin"} size={24} color={"black"} />
      <AntDesign name={"tool"} size={24} color={"black"} />
      <AntDesign name={"car"} size={24} color={"black"} />
      <AntDesign name={"addusergroup"} size={24} color={"black"} />
      <AntDesign name={"carryout"} size={24} color={"black"} />
      <AntDesign name={"deleteuser"} size={24} color={"black"} />
      <AntDesign name={"deleteusergroup"} size={24} color={"black"} />
      <AntDesign name={"man"} size={24} color={"black"} />
      <AntDesign name={"isv"} size={24} color={"black"} />
      <AntDesign name={"gift"} size={24} color={"black"} />
      <AntDesign name={"idcard"} size={24} color={"black"} />
      <AntDesign name={"medicinebox"} size={24} color={"black"} />
      <AntDesign name={"redenvelopes"} size={24} color={"black"} />
      <AntDesign name={"rest"} size={24} color={"black"} />
      <AntDesign name={"Safety"} size={24} color={"black"} />
      <AntDesign name={"wallet"} size={24} color={"black"} />
      <AntDesign name={"woman"} size={24} color={"black"} />
      <AntDesign name={"adduser"} size={24} color={"black"} />
      <AntDesign name={"bank"} size={24} color={"black"} />
      <AntDesign name={"Trophy"} size={24} color={"black"} />
      <AntDesign name={"loading1"} size={24} color={"black"} />
      <AntDesign name={"loading2"} size={24} color={"black"} />
      <AntDesign name={"like2"} size={24} color={"black"} />
      <AntDesign name={"dislike2"} size={24} color={"black"} />
      <AntDesign name={"like1"} size={24} color={"black"} />
      <AntDesign name={"dislike1"} size={24} color={"black"} />
      <AntDesign name={"bulb1"} size={24} color={"black"} />
      <AntDesign name={"rocket1"} size={24} color={"black"} />
      <AntDesign name={"select1"} size={24} color={"black"} />
      <AntDesign name={"apple1"} size={24} color={"black"} />
      <AntDesign name={"apple-o"} size={24} color={"black"} />
      <AntDesign name={"android1"} size={24} color={"black"} />
      <AntDesign name={"android"} size={24} color={"black"} />
      <AntDesign name={"aliwangwang-o1"} size={24} color={"black"} />
      <AntDesign name={"aliwangwang"} size={24} color={"black"} />
      <AntDesign name={"pay-circle1"} size={24} color={"black"} />
      <AntDesign name={"pay-circle-o1"} size={24} color={"black"} />
      <AntDesign name={"poweroff"} size={24} color={"black"} />
      <AntDesign name={"trademark"} size={24} color={"black"} />
      <AntDesign name={"find"} size={24} color={"black"} />
      <AntDesign name={"copyright"} size={24} color={"black"} />
      <AntDesign name={"sound"} size={24} color={"black"} />
      <AntDesign name={"earth"} size={24} color={"black"} />
      <AntDesign name={"wifi"} size={24} color={"black"} />
      <AntDesign name={"sync"} size={24} color={"black"} />
      <AntDesign name={"login"} size={24} color={"black"} />
      <AntDesign name={"logout"} size={24} color={"black"} />
      <AntDesign name={"reload1"} size={24} color={"black"} />
      <AntDesign name={"message1"} size={24} color={"black"} />
      <AntDesign name={"shake"} size={24} color={"black"} />
      <AntDesign name={"API"} size={24} color={"black"} />
      <AntDesign name={"appstore-o"} size={24} color={"black"} />
      <AntDesign name={"appstore1"} size={24} color={"black"} />
      <AntDesign name={"scan1"} size={24} color={"black"} />
      <AntDesign name={"exception1"} size={24} color={"black"} />
      <AntDesign name={"contacts"} size={24} color={"black"} />
      <AntDesign name={"solution1"} size={24} color={"black"} />
      <AntDesign name={"fork"} size={24} color={"black"} />
      <AntDesign name={"edit"} size={24} color={"black"} />
      <AntDesign name={"warning"} size={24} color={"black"} />
      <AntDesign name={"profile"} size={24} color={"black"} />
      <AntDesign name={"dashboard"} size={24} color={"black"} />
      <AntDesign name={"indent-left"} size={24} color={"black"} />
      <AntDesign name={"indent-right"} size={24} color={"black"} />
      <AntDesign name={"menu-unfold"} size={24} color={"black"} />
      <AntDesign name={"menu-fold"} size={24} color={"black"} />
      <AntDesign name={"antdesign"} size={24} color={"black"} />
      <AntDesign name={"alipay-square"} size={24} color={"black"} />
      <AntDesign name={"codepen-circle"} size={24} color={"black"} />
      <AntDesign name={"google"} size={24} color={"black"} />
      <AntDesign name={"amazon"} size={24} color={"black"} />
      <AntDesign name={"codepen"} size={24} color={"black"} />
      <AntDesign name={"facebook-square"} size={24} color={"black"} />
      <AntDesign name={"dropbox"} size={24} color={"black"} />
      <AntDesign name={"googleplus"} size={24} color={"black"} />
      <AntDesign name={"linkedin-square"} size={24} color={"black"} />
      <AntDesign name={"medium-monogram"} size={24} color={"black"} />
      <AntDesign name={"gitlab"} size={24} color={"black"} />
      <AntDesign name={"medium-wordmark"} size={24} color={"black"} />
      <AntDesign name={"QQ"} size={24} color={"black"} />
      <AntDesign name={"skype"} size={24} color={"black"} />
      <AntDesign name={"taobao-square"} size={24} color={"black"} />
      <AntDesign name={"alipay-circle"} size={24} color={"black"} />
      <AntDesign name={"youtube"} size={24} color={"black"} />
      <AntDesign name={"wechat"} size={24} color={"black"} />
      <AntDesign name={"twitter"} size={24} color={"black"} />
      <AntDesign name={"weibo"} size={24} color={"black"} />
      <AntDesign name={"HTML"} size={24} color={"black"} />
      <AntDesign name={"taobao-circle"} size={24} color={"black"} />
      <AntDesign name={"weibo-circle"} size={24} color={"black"} />
      <AntDesign name={"weibo-square"} size={24} color={"black"} />
      <AntDesign name={"CodeSandbox"} size={24} color={"black"} />
      <AntDesign name={"aliyun"} size={24} color={"black"} />
      <AntDesign name={"zhihu"} size={24} color={"black"} />
      <AntDesign name={"behance"} size={24} color={"black"} />
      <AntDesign name={"dribbble"} size={24} color={"black"} />
      <AntDesign name={"dribbble-square"} size={24} color={"black"} />
      <AntDesign name={"behance-square"} size={24} color={"black"} />
      <AntDesign name={"file-markdown"} size={24} color={"black"} />
      <AntDesign name={"instagram"} size={24} color={"black"} />
      <AntDesign name={"yuque"} size={24} color={"black"} />
      <AntDesign name={"slack"} size={24} color={"black"} />
      <AntDesign name={"slack-square"} size={24} color={"black"} />
    </View>
  );
};

export const styles = StyleSheet.create({
  body: {
    borderWidth: 1,
    borderColor: "red",
    // paddingLeft: 5,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
  },
});
